/**
 * Ported from the Stitch mockups' inline Tailwind config
 * (design/mockups/.../dashboard/code.html), which is what the approved
 * screenshots were rendered with. Colour and type tokens match
 * organic_celebration/DESIGN.md; the radius scale is the mockups' own, so a
 * class like `rounded-xl` means here exactly what it means there.
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f7f9ff",
        "on-background": "#1a1b2e",
        surface: "#f7f9ff",
        "surface-dim": "#d9dff0",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff3fd",
        "surface-container": "#e8edfa",
        "surface-container-high": "#e1e8f7",
        "surface-container-highest": "#d9e1f2",
        "surface-variant": "#d9e1f2",
        "surface-tint": "#624cab",
        "on-surface": "#1a1b2e",
        "on-surface-variant": "#44485f",
        "inverse-surface": "#2e3048",
        "inverse-on-surface": "#eff1fb",
        outline: "#737892",
        "outline-variant": "#c3c8dc",
        primary: "#624cab",
        "on-primary": "#ffffff",
        "primary-container": "#c1cefe",
        "on-primary-container": "#1a1b2e",
        "inverse-primary": "#a0ddff",
        "primary-fixed": "#e2e6ff",
        "primary-fixed-dim": "#c1cefe",
        "on-primary-fixed": "#17023f",
        "on-primary-fixed-variant": "#4a357f",
        secondary: "#485bba",
        "on-secondary": "#ffffff",
        "secondary-container": "#30467f",
        "on-secondary-container": "#ffffff",
        "secondary-fixed": "#dfe4ff",
        "secondary-fixed-dim": "#c1cefe",
        "on-secondary-fixed": "#101643",
        "on-secondary-fixed-variant": "#4f5fa8",
        tertiary: "#397597",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#397597",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#d4f0ff",
        "tertiary-fixed-dim": "#a0ddff",
        "on-tertiary-fixed": "#05202c",
        "on-tertiary-fixed-variant": "#1a5e7a",
        error: "#b3261e",
        "on-error": "#ffffff",
        "error-container": "#f9dedc",
        "on-error-container": "#8c1d18",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        sidebar_width: "260px",
        topbar_height: "80px",
      },
      fontFamily: {
        "display-lg": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "title-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-sm": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
