/**
 * Ported from the Stitch mockups' inline Tailwind config
 * (design/mockups/.../dashboard/code.html), which is what the approved
 * screenshots were rendered with. Colour and type tokens match
 * organic_celebration/DESIGN.md; the radius scale is the mockups' own, so a
 * class like `rounded-xl` means here exactly what it means there.
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f5fafa",
        "on-background": "#171d1d",
        surface: "#f5fafa",
        "surface-dim": "#d5dbdb",
        "surface-bright": "#f5fafa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff5f4",
        "surface-container": "#e9efef",
        "surface-container-high": "#e4e9e9",
        "surface-container-highest": "#dee4e3",
        "surface-variant": "#dee4e3",
        "surface-tint": "#006a69",
        "on-surface": "#171d1d",
        "on-surface-variant": "#3d4949",
        "inverse-surface": "#2c3132",
        "inverse-on-surface": "#ecf2f1",
        outline: "#6d7a79",
        "outline-variant": "#bcc9c8",
        primary: "#006a69",
        "on-primary": "#ffffff",
        "primary-container": "#2faead",
        "on-primary-container": "#003c3b",
        "inverse-primary": "#64d8d7",
        "primary-fixed": "#82f5f3",
        "primary-fixed-dim": "#64d8d7",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#00504f",
        secondary: "#b6231f",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd574b",
        "on-secondary-container": "#5c0004",
        "secondary-fixed": "#ffdad6",
        "secondary-fixed-dim": "#ffb4ab",
        "on-secondary-fixed": "#410002",
        "on-secondary-fixed-variant": "#93000a",
        tertiary: "#954920",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#e28658",
        "on-tertiary-container": "#5e2300",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#ffb693",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#77320a",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        sidebar_width: "260px",
        topbar_height: "80px",
      },
      fontFamily: {
        "display-lg": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "title-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-sm": ["Be Vietnam Pro", "sans-serif"],
        "label-md": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
